/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

struct t___139;
struct t___100;
struct t___8;
struct t___83;
struct t___108;
union t___111;
union t___86;
union t___135;
union t___148;
union t___79;
union t___143;
struct t___125;
struct t___66;
struct t___70;
union t___117;
struct t___94;
struct t___121;
extern int gettimeofday(struct t___121 *tv , void *tz ) ;
int o___64  =    0;
extern int pthread_cond_broadcast(union t___135 *cond ) ;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned long alignment , unsigned long size ) ;
void o___65(void) ;
struct t___66 {
   struct t___66 *f___67 ;
   struct t___66 *f___68 ;
};
typedef struct t___66 o___69;
struct t___70 {
   int f___71 ;
   unsigned int f___72 ;
   int f___73 ;
   unsigned int f___74 ;
   int f___75 ;
   short f___76 ;
   short f___77 ;
   o___69 f___78 ;
};
union t___79 {
   struct t___70 f___80 ;
   char f___81[40] ;
   long f___82 ;
};
struct t___83 {
   unsigned int f___84 ;
   unsigned int f___85 ;
};
union t___86 {
   unsigned long long f___87 ;
   struct t___83 f___88 ;
};
extern int pthread_join(void *thread , void **value_ptr ) ;
typedef union t___117 o___89;
extern unsigned long strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
typedef union t___79 o___90;
typedef union t___143 o___91;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) pthread_mutex_init)(o___90 *__mutex ,
                                                                                                         o___91 const   *__mutexattr ) ;
typedef long o___92;
typedef long o___93;
struct t___94 {
   o___93 f___95 ;
   o___92 f___96 ;
};
extern int printf(char const   *format  , ...) ;
char **o___97  =    (char **)0;
extern int pthread_cond_signal(union t___135 *cond ) ;
char **o___98  =    (char **)0;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
extern int unlink(char const   *filename ) ;
void o___99(unsigned long *l___1054 , unsigned long *l___1055 ) ;
struct t___100 {
   struct t___100 *f___101 ;
   struct t___100 *f___102 ;
   unsigned long f___103 ;
};
unsigned long o___104[2] ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_mutex_lock(union t___79 *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned long namelen ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int fprintf(struct t___8 *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
struct t___100 *o___105[2] ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
int main(int l___1043 , char **l___1044 , char **l___1045 ) ;
typedef struct t___8 o___106;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned long len , int prot ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double ceil(double x ) ;
struct t___100 *o___107[2] ;
struct t___108 {
   unsigned int f___109 ;
   unsigned int f___110 ;
};
union t___111 {
   unsigned long long f___112 ;
   struct t___108 f___113 ;
};
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int pthread_cond_wait(union t___135 *cond , union t___135 *mutex ) ;
extern void perror(char const   *str ) ;
void o___114(void) ;
extern long write(int filedes , void *buf , unsigned long nbyte ) ;
typedef union t___135 o___115;
typedef union t___148 o___116;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) pthread_cond_init)(o___115 * __restrict  __cond ,
                                                                                                        o___116 const   * __restrict  __cond_attr ) ;
union t___117 {
   char f___118[56] ;
   long f___119 ;
};
extern int ptrace(int request , void *pid , void *addr , int data ) ;
void o___120(void) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
struct t___121 {
   long f___122 ;
   long f___123 ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned long nel , unsigned long width , int (*compar)(void *a ,
                                                                                       void *b ) ) ;
extern long time(long *tloc ) ;
void o___124(void) ;
struct t___125 {
   union t___111 f___126 ;
   union t___86 f___127 ;
   unsigned int f___128[2] ;
   unsigned int f___129[2] ;
   unsigned int f___130 ;
   unsigned int f___131 ;
   unsigned int f___132[2] ;
};
extern int rand() ;
extern long read(int filedes , void *buf , unsigned long nbyte ) ;
typedef unsigned long o___133;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
void o___134(void) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int snprintf(char *str , unsigned long size , char const   *format  , ...) ;
extern void *malloc(unsigned long size ) ;
extern int nanosleep(struct t___94  const  *__requested_time , struct t___94 *__remaining ) ;
union t___135 {
   struct t___125 f___136 ;
   char f___137[48] ;
   long long f___138 ;
};
struct t___139 {
   struct t___139 *f___140 ;
   unsigned long f___141 ;
   struct t___139 *f___142 ;
};
extern int pthread_mutex_unlock(union t___79 *mutex ) ;
union t___143 {
   char f___144[4] ;
   int f___145 ;
};
extern int atoi(char const   *s ) ;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,3))) pthread_create)(o___133 * __restrict  __newthread ,
                                                                                             o___89 const   * __restrict  __attr ,
                                                                                             void *(*__start_routine)(void * ) ,
                                                                                             void * __restrict  __arg ) ;
void o___146(void) ;
void o___147(void) ;
union t___148 {
   char f___149[4] ;
   int f___150 ;
};
extern int fseek(struct t___8 *stream , long offs , int whence ) ;
extern int fscanf(struct t___8 *stream , char const   *format  , ...) ;
void o___151(void) ;
void o___120(void)
{


  {
  o___114();
  o___65();
  o___146();
}
}
void o___99(unsigned long *l___1054 , unsigned long *l___1055 )
{
  unsigned long l___1057[2] ;
  struct t___139 *l___1058[2] ;
  struct t___139 *l___1059[2] ;
  struct t___139 *l___1060 ;
  struct t___139 *l___1061 ;
  struct t___139 *l___1062 ;
  struct t___139 *l___1063 ;
  struct t___100 *l___1064 ;
  struct t___100 *l___1065 ;
  struct t___100 *l___1066 ;
  struct t___100 *l___1067 ;
  struct t___100 *l___1068 ;
  void *l___1069 ;
  void *l___1070 ;
  void *l___1071 ;
  void *l___1072 ;
  void *l___1073 ;
  void *l___1074 ;
  void *l___1075 ;
  void *l___1076 ;
  void *l___1077 ;
  unsigned long l___1078 ;

  {
  {
  l___1078 = 4;
  }
  while (1) {
    switch (l___1078) {
    case 7: ;
    return;
    break;
    case 3: ;
    if (! ((l___1059[0UL])->f___141 & 1UL)) {
      {
      l___1078 = 6;
      }
    } else {
      {
      l___1078 = 2;
      }
    }
    break;
    case 5:
    l___1059[1UL] = (l___1059[1UL])->f___142;
    l___1077 = malloc(24UL);
    l___1068 = (struct t___100 *)l___1077;
    l___1068->f___103 = l___1057[(unsigned long )((int )o___104[0UL]) % 2UL] * l___1057[(unsigned long )((int )l___1057[0UL]) % 2UL];
    l___1068->f___102 = (o___107[(unsigned long )((int )(o___107[1UL])->f___103) % 2UL])->f___102;
    l___1068->f___101 = o___107[(unsigned long )((int )(o___107[1UL])->f___103) % 2UL];
    ((o___107[(unsigned long )((int )(o___107[1UL])->f___103) % 2UL])->f___102)->f___101 = l___1068;
    (o___107[(unsigned long )((int )(o___107[1UL])->f___103) % 2UL])->f___102 = l___1068;
    {
    l___1078 = 2;
    }
    break;
    case 4:
    l___1058[0] = (struct t___139 *)0;
    l___1058[1] = (struct t___139 *)0;
    l___1059[0] = (struct t___139 *)0;
    l___1059[1] = (struct t___139 *)0;
    l___1057[0UL] = (*(l___1054 + 0UL) >> 11UL) | (*(l___1054 + 0UL) << 53UL);
    l___1057[1UL] = *(l___1054 + 0UL) * l___1057[0UL];
    o___104[0UL] = (*(l___1054 + 0UL) | 588742733UL) - (l___1057[0UL] << 7UL);
    o___104[1UL] = *(l___1054 + 0UL) + ((l___1057[0UL] >> 15UL) | (l___1057[0UL] << 49UL));
    l___1069 = malloc(24UL);
    l___1060 = (struct t___139 *)l___1069;
    l___1060->f___142 = l___1060;
    l___1060->f___140 = l___1060;
    l___1058[0UL] = l___1060;
    l___1059[0UL] = l___1060;
    l___1060->f___141 = 0UL;
    l___1070 = malloc(24UL);
    l___1061 = (struct t___139 *)l___1070;
    l___1061->f___141 = (*(l___1054 + 0UL) >> ((l___1057[0UL] & 7UL) | 1UL)) & (o___104[1UL] + o___104[0UL]);
    l___1061->f___142 = (l___1059[0UL])->f___142;
    l___1061->f___140 = l___1059[0UL];
    ((l___1059[0UL])->f___142)->f___140 = l___1061;
    (l___1059[0UL])->f___142 = l___1061;
    l___1059[0UL] = (l___1059[0UL])->f___142;
    l___1071 = malloc(24UL);
    l___1062 = (struct t___139 *)l___1071;
    l___1062->f___142 = l___1062;
    l___1062->f___140 = l___1062;
    l___1058[1UL] = l___1062;
    l___1059[1UL] = l___1062;
    l___1062->f___141 = 0UL;
    l___1072 = malloc(24UL);
    l___1063 = (struct t___139 *)l___1072;
    l___1063->f___141 = *(l___1054 + 0UL) >> 1UL;
    l___1063->f___142 = (l___1059[1UL])->f___142;
    l___1063->f___140 = l___1059[1UL];
    ((l___1059[1UL])->f___142)->f___140 = l___1063;
    (l___1059[1UL])->f___142 = l___1063;
    l___1059[1UL] = (l___1059[1UL])->f___142;
    l___1073 = malloc(24UL);
    l___1064 = (struct t___100 *)l___1073;
    l___1064->f___102 = l___1064;
    l___1064->f___101 = l___1064;
    o___105[0UL] = l___1064;
    o___107[0UL] = l___1064;
    l___1064->f___103 = 0UL;
    l___1074 = malloc(24UL);
    l___1065 = (struct t___100 *)l___1074;
    l___1065->f___103 = (*(l___1054 + 0UL) ^ 839817244UL) << ((((l___1057[0UL] & 366609898UL) >> 3UL) & 7UL) | 1UL);
    l___1065->f___102 = (o___107[0UL])->f___102;
    l___1065->f___101 = o___107[0UL];
    ((o___107[0UL])->f___102)->f___101 = l___1065;
    (o___107[0UL])->f___102 = l___1065;
    o___107[0UL] = (o___107[0UL])->f___102;
    l___1075 = malloc(24UL);
    l___1066 = (struct t___100 *)l___1075;
    l___1066->f___102 = l___1066;
    l___1066->f___101 = l___1066;
    o___105[1UL] = l___1066;
    o___107[1UL] = l___1066;
    l___1066->f___103 = 0UL;
    l___1076 = malloc(24UL);
    l___1067 = (struct t___100 *)l___1076;
    l___1067->f___103 = (*(l___1054 + 0UL) >> (((l___1057[0UL] >> 1UL) & 7UL) | 1UL)) - (o___104[1UL] + (l___1057[1UL] + o___104[0UL]));
    l___1067->f___102 = (o___107[1UL])->f___102;
    l___1067->f___101 = o___107[1UL];
    ((o___107[1UL])->f___102)->f___101 = l___1067;
    (o___107[1UL])->f___102 = l___1067;
    o___107[1UL] = (o___107[1UL])->f___102;
    {
    l___1078 = 1;
    }
    break;
    case 0: ;
    if (((o___107[0UL])->f___103 >> 2UL) & 1UL) {
      {
      l___1078 = 3;
      }
    } else {
      {
      l___1078 = 2;
      }
    }
    break;
    case 2:
    *(l___1055 + 0UL) = ((l___1057[0UL] * l___1057[1UL] & ((l___1059[0UL])->f___141 ^ (l___1059[1UL])->f___141)) << (((((o___104[0UL] * o___104[1UL] >> ((((o___107[0UL])->f___103 - (o___107[1UL])->f___103) & 15UL) | 1UL)) | (o___104[0UL] * o___104[1UL] << (64UL - ((((o___107[0UL])->f___103 - (o___107[1UL])->f___103) & 15UL) | 1UL)))) >> 3UL) & 15UL) | 1UL)) | ((l___1057[0UL] * l___1057[1UL] & ((l___1059[0UL])->f___141 ^ (l___1059[1UL])->f___141)) >> (64UL - (((((o___104[0UL] * o___104[1UL] >> ((((o___107[0UL])->f___103 - (o___107[1UL])->f___103) & 15UL) | 1UL)) | (o___104[0UL] * o___104[1UL] << (64UL - ((((o___107[0UL])->f___103 - (o___107[1UL])->f___103) & 15UL) | 1UL)))) >> 3UL) & 15UL) | 1UL)));
    {
    l___1078 = 7;
    }
    break;
    case 1: ;
    if ((l___1057[1UL] >> 2UL) & 1UL) {
      {
      l___1078 = 5;
      }
    } else {
      {
      l___1078 = 0;
      }
    }
    break;
    case 6:
    l___1059[(unsigned long )((int )(o___107[1UL])->f___103) % 2UL] = (l___1059[(unsigned long )((int )(o___107[1UL])->f___103) % 2UL])->f___142;
    l___1057[(unsigned long )((int )(o___107[0UL])->f___103) % 2UL] |= (o___104[(unsigned long )((int )(l___1059[1UL])->f___141) % 2UL] & 7UL) << 2UL;
    (l___1059[(unsigned long )((int )o___104[1UL]) % 2UL])->f___141 = l___1057[1UL] + l___1057[1UL];
    {
    l___1078 = 2;
    }
    break;
    }
  }
}
}
void o___151(void)
{


  {
  o___124();
  o___134();
  o___147();
  return;
}
}
void o___124(void)
{


  {
  return;
}
}
void o___114(void)
{


  {

}
}
int main(int l___1043 , char **l___1044 , char **l___1045 )
{
  unsigned long l___1047[1] ;
  unsigned long l___1048[1] ;
  int l___1049 ;
  unsigned long l___1050 ;
  int l___1051 ;

  {
  o___120();
  o___64 = l___1043;
  o___97 = l___1044;
  o___98 = l___1045;
  o___151();
  if (l___1043 != 2) {
    printf("Call this program with %i arguments\n", 1);
    exit(-1);
  }
  l___1049 = 0;
  while (l___1049 < 1) {
    l___1050 = strtoul((char const   *)*(l___1044 + (l___1049 + 1)), (char const   *)0,
                       10);
    l___1047[l___1049] = l___1050;
    l___1049 ++;
  }
  o___99((unsigned long *)(l___1047), (unsigned long *)(l___1048));
  l___1051 = 0;
  while (l___1051 < 1) {
    printf("%lu\n", l___1048[l___1051]);
    l___1051 ++;
  }
  return (0);
}
}
void o___146(void)
{


  {

}
}
void o___134(void)
{


  {
  return;
}
}
void o___65(void)
{
  int l___1023 ;

  {
  l___1023 = 0;
  while (l___1023 < 2) {
    o___104[l___1023] = 0UL;
    l___1023 ++;
  }
}
}
void o___147(void)
{


  {
  return;
}
}
